name: 'Compare JSON Files'
description: 'Compares two JSON files in the repository'
inputs:
  file1:
    description: 'Path to the first JSON file'
    required: true
  file2:
    description: 'Path to the second JSON file'
    required: true
outputs:
  areEqual:
    description: 'True if the JSON files are equal, false otherwise'
runs:
  using: node20
  main: dist/index.js
